server {
    listen 80;
    server_name localhost;
    
    # Diretório raiz do site
    root /var/www/technova;
    index index.html;

    # Logs personalizados
    access_log /var/log/nginx/technova_access.log;
    error_log /var/log/nginx/technova_error.log;

    # Configuração de erro 404 customizada
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    # Tenta carregar o arquivo, depois o diretório, senão retorna 404
    location / {
        try_files $uri $uri/ =404;
    }
}